# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/drmedFM',
                'doc_host': 'https://enekocm.github.io',
                'git_url': 'https://github.com/enekocm/drmedFM',
                'lib_path': 'drmedFM'},
  'syms': { 'drmedFM.Datamodule': { 'drmedFM.Datamodule.hellosum': ('datamodule.html#hellosum', 'drmedFM/Datamodule.py'),
                                    'drmedFM.Datamodule.hellosum2': ('datamodule.html#hellosum2', 'drmedFM/Datamodule.py')},
            'drmedFM.Dataset': {'drmedFM.Dataset.foo': ('dataset.html#foo', 'drmedFM/Dataset.py')},
            'drmedFM.core': {'drmedFM.core.foo': ('dataset.html#foo', 'drmedFM/core.py')}}}
