# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_Datamodule.ipynb.

# %% auto 0
__all__ = ['hellosum', 'hellosum2']

# %% ../nbs/01_Datamodule.ipynb 4
def hellosum(a:int 
             , b:int): 
    "A sum function"
    yes = a + b
    return yes


# %% ../nbs/01_Datamodule.ipynb 6
def hellosum2(a, b): 
    return a + b
